---
# tasks file for ansible-role-collectd
- name: Assertions
  assert:
      that: ansible_os_family in [ 'Debian', 'OpenBSD' ]

- name: APT install
  when: ansible_pkg_mgr == 'apt'
  apt:
      name: collectd
      install_recommends: no
      state: present
      update_cache: yes
      cache_valid_time: 3600

- name: pkg install
  when: ansible_pkg_mgr == 'openbsd_pkg'
  openbsd_pkg:
      name: '{{ openbsd_collectd_version[ansible_distribution_release] }}'
      state: present

- name: Create configuration directory
  file:
      path: '{{ collectd_conf[ansible_os_family] }}.d'
      owner: root
      group: 0
      mode: 0o0755
      state: directory

- name: Basic configuration
  template:
      src: collectd.conf
      dest: /etc/collectd.conf
      owner: root
      group: 0
      mode: 0o0644
  notify:
  - Restart collectd

- name: Copy configuration templates
  with_fileglob:
  - templates/collectd.conf.d/*.conf
  - '{{ playbook_dir }}/templates/collectd.conf.d/*.conf'
  template:
      src: '{{ item }}'
      dest: '{{ collectd_conf[ansible_os_family] }}.d'
      owner: root
      group: 0
      mode: 0o0644
  notify:
  - Restart collectd

- name: Alias mail to root
  lineinfile:
      dest: '{{ aliases_file[ansible_os_family] }}'
      create: yes
      line: '{{ collectd_user[ansible_os_family] }}: root'
      regexp: '{{ collectd_user[ansible_os_family] }}:'
  notify:
      - Update SMTPd database

- name: Enabled service
  service:
      name: collectd
      state: started
      enabled: yes
