---
# handlers file for ansible-role-collectd

- name: Restart collectd
  service:
      name: collectd
      state: restarted

- name: Update SMTPd database
  when: ansible_os_family == 'OpenBSD'
  command: /usr/bin/newaliases
